-- CreateEnum
CREATE TYPE "ForumCategory" AS ENUM ('GENERAL_DISCUSSION', 'ACADEMIC_HELP', 'STUDENT_LIFE', 'CAREER_AND_INTERNSHIPS', 'TECH_AND_PROGRAMMING', 'CAMPUS_SERVICES');

-- AlterTable
ALTER TABLE "Question" ADD COLUMN     "category" "ForumCategory" NOT NULL DEFAULT 'GENERAL_DISCUSSION';
